from __future__ import annotations

from typing import Any, Awaitable, Callable, Protocol, Sequence, runtime_checkable

from ..contracts import Chunk, Conversation, Document, ScoredChunk, Turn
from .types import SparseVector, VectorRecord


@runtime_checkable
class VectorStore(Protocol):
    async def upsert(self, records: Sequence[VectorRecord]) -> None: ...

    async def search(self, query_dense: list[float], *, tenant_id: str, top_k: int = 100, query_sparse: SparseVector | None = None, filters: dict | None = None) -> list[ScoredChunk]: ...

    async def deleteDoc(self, doc_id: str, tenant_id: str) -> None: ...

    async def count(self, tenant_id: str | None = None) -> int: ...


@runtime_checkable
class LexicalIndex(Protocol):
    async def add(self, chunks: Sequence[Chunk]) -> None: ...

    async def search(self, query: str, *, tenant_id: str, top_k: int = 100, filters: dict | None = None) -> list[ScoredChunk]: ...

    async def deleteDoc(self, doc_id: str, tenant_id: str) -> None: ...


@runtime_checkable
class DocStore(Protocol):
    async def getByHash(self, tenant_id: str, content_hash: str) -> Document | None: ...

    async def getDoc(self, tenant_id: str, doc_id: str) -> Document | None: ...

    async def listDocs(self, tenant_id: str) -> list[Document]: ...

    async def upsertDoc(self, doc: Document) -> None: ...

    async def putChunks(self, chunks: Sequence[Chunk]) -> None: ...

    async def deleteChunks(self, doc_id: str, tenant_id: str) -> None: ...

    async def getChunk(self, tenant_id: str, chunk_id: str) -> Chunk | None: ...

    async def listChunks(self, tenant_id: str, *, limit: int | None = None) -> list[Chunk]: ...


@runtime_checkable
class SessionStore(Protocol):
    async def get(self, tenant_id: str, session_id: str) -> Conversation: ...

    async def append(self, tenant_id: str, session_id: str, turn: Turn, *, max_turns: int = 20) -> None: ...


@runtime_checkable
class Cache(Protocol):
    async def get(self, key: str) -> Any | None: ...

    async def set(self, key: str, value: Any, ttl_s: int | None = None) -> None: ...

    async def getOrCompute(self, key: str, compute: Callable[[], Awaitable[Any]], ttl_s: int | None = None) -> Any: ...

    async def invalidate(self, key: str) -> None: ...
